### ISSUE TITLE
[feature request] eval specific function returns

### ISSUE THREAD

**Issue by ahxxm** [willnode/deobfuscator#1]
for example the script has a string obfuscate function for access, defined like this:

```javascript
var _0x131 = function(index, key){return obfs();}
```

then access becomes:

```javascript
this[_0x131('0x2', '3W*K')](_0x131('0x3', '8uoO'))
```

there will be tons of _0x131 call, but currently I need to:

- copy _0x131 definition to console and eval
- select one full call, click eval
- select next....

**Comment by ahxxm** [comment]
one workaround for select is to use built-in Ctrl-f: next match, eval, next match .. but sill not scalable..  
![image](https://user-images.githubusercontent.com/1286225/58631286-b32a7700-8314-11e9-9e3e-6d891f493c52.png)

**Comment by willnode** [comment]
I think i get your idea. A "function subtitution". It behaves similar to *array subtitution* but does eval to a function. 

One challenging problem to this idea is when that function requires a variable or a function that's outside their scope, e.g. `Window` -- but I think it's far less common anyway so let's see if I can make it happen.

**Comment by ahxxm** [comment]
I wrote an AHK script to do repetitive mouse clicks..

In my case the function is not self-contained, it does require a variable and this variable requires additional initialization step. I had to eval it before use eval button..

**Comment by willnode** [comment]
This is now can be done using [eval push and pop](https://github.com/willnode/deobfuscator#push-evalpush-and-pop-evalpop) (new feature). Thanks for the suggestion.
