### ISSUE TITLE
npm build error

### ISSUE THREAD

**Issue by kikikikikinanana** [willnode/deobfuscator#2]
> parcel build ./node_modules/monaco-editor/esm/vs/language/typescript/ts.worker.js --no-source-maps

× Build failed.
@parcel/optimizer-terser: Unexpected token: operator (*)
  24828 |             /** @returns {number}*/
> 24829 |             /**/*/
>       |                ^ Unexpected token: operator (*)
  24830 |             /*var x = function(name) { return name.length; }*/
  24831 | } else // Try to recognize this pattern when node is initializer of variable declaration and JSDoc comments ar
It's likely that Terser doesn't support this syntax yet.
[Error: Error opening directory]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deobfuscator@ build-worker: `parcel build ./node_modules/monaco-editor/esm/vs/language/typescript/ts.worker.js --no-source-maps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deobfuscator@ build-worker script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JINHYEOK\AppData\Roaming\npm-cache\_logs\2021-01-22T21_58_21_024Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deobfuscator@ start: `npm run build-worker && parcel serve src/index.html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deobfuscator@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JINHYEOK\AppData\Roaming\npm-cache\_logs\2021-01-22T21_58_21_044Z-debug.log

npm install and npm start....

debug.log

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-worker'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.10.0
4 verbose run-script [ 'prebuild-worker', 'build-worker', 'postbuild-worker' ]
5 info lifecycle deobfuscator@~prebuild-worker: deobfuscator@
6 info lifecycle deobfuscator@~build-worker: deobfuscator@
7 verbose lifecycle deobfuscator@~build-worker: unsafe-perm in lifecycle true
8 verbose lifecycle deobfuscator@~build-worker: PATH: C:\Users\JINHYEOK\AppData\Roaming\nvm\v14.10.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\JINHYEOK\Documents\카카오톡 받은 파일\deobfuscator-master\node_modules\.bin;C:\Users\JINHYEOK\AppData\Roaming\nvm\v14.10.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\JINHYEOK\Documents\카카오톡 받은 파일\deobfuscator-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python39\Scripts\;C:\Python39\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Program Files\Python38\Scripts\;C:\Program Files\Python38\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Tesseract-OCR;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Gradle\gradle-4.8.1\bin;C:\ProgramData\chocolatey\bin;C:\Users\JINHYEOK\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Java\jre1.8.0_231\bin;;C:\Program Files (x86)\Universal Extractor;C:\Program Files (x86)\Universal Extractor\bin;C:\Users\JINHYEOK\anaconda3;C:\Users\JINHYEOK\anaconda3\Library\mingw-w64\bin;C:\Users\JINHYEOK\anaconda3\Library\usr\bin;C:\Users\JINHYEOK\anaconda3\Library\bin;C:\Users\JINHYEOK\anaconda3\Scripts;C:\Users\JINHYEOK\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm Edu 2020.1.1\bin;;C:\Users\JINHYEOK\AppData\Local\GitHubDesktop\bin;C:\Program Files\Bandizip\;C:\Users\JINHYEOK\AppData\Roaming\npm;C:\Users\JINHYEOK\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\JINHYEOK\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle deobfuscator@~build-worker: CWD: C:\Users\JINHYEOK\Documents\카카오톡 받은 파일\deobfuscator-master
10 silly lifecycle deobfuscator@~build-worker: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'parcel build ./node_modules/monaco-editor/esm/vs/language/typescript/ts.worker.js --no-source-maps'
10 silly lifecycle ]
11 silly lifecycle deobfuscator@~build-worker: Returned: code: 1  signal: null
12 info lifecycle deobfuscator@~build-worker: Failed to exec build-worker script
13 verbose stack Error: deobfuscator@ build-worker: `parcel build ./node_modules/monaco-editor/esm/vs/language/typescript/ts.worker.js --no-source-maps`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\JINHYEOK\AppData\Roaming\nvm\v14.10.0\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\JINHYEOK\AppData\Roaming\nvm\v14.10.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1047:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid deobfuscator@
15 verbose cwd C:\Users\JINHYEOK\Documents\카카오톡 받은 파일\deobfuscator-master
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-worker"
18 verbose node v14.10.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error deobfuscator@ build-worker: `parcel build ./node_modules/monaco-editor/esm/vs/language/typescript/ts.worker.js --no-source-maps`
22 error Exit status 1
23 error Failed at the deobfuscator@ build-worker script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by willnode** [comment]
You probably need to update your Node.js

**Comment by willnode** [comment]
Closed as no activities further.
